### PR TITLE
s2i image for superset

### PR DESCRIPTION
**Pull request by shawnzhu**
It includes:

1. build container image by using s2i
2. upgrade apache superset to 1.1.0
3. test built container image by using container-structure-test

### CODE REVIEW

**Comment by rimolive** [comment]
LGTM, but could you squash the commits?

**Comment by LaVLaS** [comment]
Is this the same build files for the Superset 1.1.0 image that was used in https://github.com/opendatahub-io/odh-manifests/pull/426?

**Comment by shawnzhu** [comment]
> Is this the same build files for the Superset 1.1.0 image that was used in opendatahub-io/odh-manifests#426?

No. I saw it uses `quay.io/internaldatahub/superset:1.1.0` in odh-manifests no idea how it's built

https://github.com/opendatahub-io/odh-manifests/blob/3b777afec8abde7f660112b71dd16afa871ed04c/superset/base/params.env#L19

**Comment by shawnzhu** [comment]
If mouting `superset_config.py` at `/etc/superset` is a requirement:

https://github.com/opendatahub-io/odh-manifests/blob/3b777afec8abde7f660112b71dd16afa871ed04c/superset/base/deployment.yaml#L36-L38

I will need a new PR to make it in this repo since it expects `superset_config.py` shows up under `/opt/app-root/src/pythonpath`

**Comment by maulikjs** [comment]
Hey @shawnzhu ! Thank you for the MR.
The image that we use for `quay.io/internaldatahub/superset:1.1.0` is built from this repo: https://github.com/amancevice/docker-superset

**Comment by shawnzhu** [comment]
@maulikjs Thanks for the pointer! the `Dockerfile` from https://github.com/amancevice/docker-superset looks like that of the official one from apache/superset. Have you thought about adopting the official one? (which I use for staging deployment works fine to me)

One thing I need help to understand is about whether building superset itself from source for such image, since it installs `apache-superset` from   pypi.org instead of downloading source from github. is this a requirement?

**Comment by shawnzhu** [comment]
@maulikjs @rimolive May I ask any more comments? are you saying these changes should go to https://github.com/amancevice/docker-superset instead of this repo or anymore action I need to take to get this PR merged?

**Comment by maulikjs** [comment]
> Have you thought about adopting the official one
@shawnzhu  yes we have! We haven't made the switch yet because there aren't any tagged releases for the official docker image for superset as of 1.1.0. They are going to have one for 1.2.0 which is when we plan on switching over to the official one.

**Comment by shawnzhu** [comment]
Superset 1.2.0 just released: https://github.com/apache/superset/releases/tag/1.2.0

@maulikjs @rimolive should I update this PR to pick up Superset 1.2.0 or patching https://github.com/amancevice/docker-superset instead?

**Comment by maulikjs** [comment]
Hey @shawnzhu 
I was about to say, yeah lets do that! Actually lets build superset 1.2.0 from the official source!
I can help you with that if you want :)
Thanks for contributing!

**Comment by shawnzhu** [comment]
I've updated this PR to install superset 1.2.0

Questions:

1. list of requirements for building superset image by using s2i?
2. Speaking of building superset from the official source, the frontend part needs npm while the python part is just `pip install -e .`. I didn't see that much difference between https://github.com/amancevice/docker-superset and the official one especially the final images are both based on debian. So I'm curious if it needs a `Dockerfile` to perform staged build or there's a better example for multi-staged build with s2i w/o a `Dockerfile`.

**Review by maulikjs — APPROVED** [review]

**Review by rimolive — APPROVED** [review]

**Pull request merged**
